# Generated by Django 6.0.2 on 2026-02-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weather Searches',
                'ordering': ['-searched_at'],
            },
        ),
    ]
